apiVersion: skaffold/v4beta3
kind: Config
manifests:
    rawYaml:
        - ./infra/k8s/*
build:
    local:
        push: false
    artifacts:
        - image: ankur08092002/auth
          context: auth
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: '*.ts'
                    dest: .
        - image: ankur08092002/client
          context: client
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: '*.js'
                    dest: .
        - image: ankur08092002/tickets
          context: tickets
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: '*.ts'
                    dest: .
        - image: ankur08092002/orders
          context: orders
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: '*.ts'
                    dest: .
        - image: ankur08092002/expiration
          context: expiration
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: '*.ts'
                    dest: .
        - image: ankur08092002/payments
          context: payments
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: '*.ts'
                    dest: .
