apiVersion: apps/v1
kind: Deployment
metadata:
    name: tickets-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: tickets
    template:
        metadata:
            labels:
                app: tickets
        spec:
            containers:
                - name: tickets
                  image: ankur08092002/tickets
                  # Add this when you have stored your secrets objects in the kubernetes
                  env:
                      - name: MONGO_URI
                        value: 'mongodb://tickets-mongo-srv:27017/tickets'
                      - name: JWT_KEY
                        valueFrom:
                            secretKeyRef:
                                name: jwt-secret
                                key: JWT_KEY
                      - name: NATS_URL
                        value: http://nats-srv:4222
                      - name: NATS_CLUSTER_ID
                        value: ticketing
                      - name: NATS_CLIENT_ID
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
    name: tickets-srv
spec:
    selector:
        app: tickets
    ports:
        - name: tickets
          protocol: TCP
          port: 3000
          targetPort: 3000
